# Generated by Django 5.2 on 2025-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('shortCode', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessCount', models.IntegerField(default=0)),
            ],
        ),
    ]
